Upgrade to Buildroot 2025.05

diff --git a/package/mender/S42mender b/package/mender/S42mender
--- a/package/mender/S42mender
+++ b/package/mender/S42mender
@@ -2,36 +2,24 @@
 #
 # Starts mender service.
 #
+DAEMON="mender"
+DAEMON_PATH="/usr/bin/mender"
+PIDFILE="/var/run/${DAEMON}.pid"
+DAEMON_ARGS="daemon"
 
 start() {
-	# If /var/lib/mender is a symlink to /var/run/mender, and
-	#   - the filesystem is RO (i.e. we can not rm the symlink),
-	#     create the directory pointed to by the symlink.
-	#   - the filesystem is RW (i.e. we can rm the symlink),
-	#     replace the symlink with an actual directory
-	if [ -L /var/lib/mender \
-	     -a "$(readlink /var/lib/mender)" = "/var/run/mender" ]
-	then
-		if rm -f /var/lib/mender >/dev/null 2>&1; then
-			mkdir -p /var/lib/mender
-		else
-			echo "No persistent location to store mender data. Data will be lost"
-			echo "at reboot. Are you sure this is what you want to do?"
-			mkdir -p "$(readlink /var/lib/mender)"
-		fi
-	fi
-
 	printf "Starting mender service: "
 	umask 077
-
-	start-stop-daemon -S -q -b -m -p /var/run/mender.pid \
-		--exec /usr/bin/mender -- -daemon
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	start-stop-daemon -bmSqp "$PIDFILE" -x ${DAEMON_PATH} -- ${DAEMON_ARGS}
+	status=$?
+	[ "${status}" = 0 ] && echo "OK" || echo "FAIL"
 }
+
 stop() {
 	printf "Stopping mender service: "
-	start-stop-daemon -K -q -p /var/run/mender.pid
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	start-stop-daemon -Kqp "$PIDFILE"
+	status=$?
+	[ "${status}" = 0 ] && echo "OK" || echo "FAIL"
 }
 restart() {
 	stop
@@ -49,7 +37,7 @@ case "$1" in
 		restart
 		;;
 	*)
-		echo "Usage: $0 {start|stop|restart}"
+		echo "Usage: $0 {start|stop|reload|restart}"
 		exit 1
 esac
 
